import Head from 'next/head'
import Image from 'next/image'
import {useSelector, useDispatch} from 'react-redux'
import {toggleTheme} from "../slices/themeSlice"
export default function Home() {
  const dispatch = useDispatch()
  const theme = useSelector(state => state.theme.isDarkMode)
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
        <button onClick={() => dispatch(toggleTheme())} className='w-full h-10 bg-red-400/50'>Decrement</button>

        <p>The value of theme is {`${theme}`}</p>
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span >
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

