import Head from 'next/head'
import Image from 'next/image'
import {useSelector, useDispatch} from 'react-redux'
import { useContext } from 'react'
import { ThemeContext } from './_app'


export default function Home(props) {
  const theme = useContext(ThemeContext)

  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8"/>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

    </Head>
      <main>
        <p>Main Tag</p>
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <h1>Footer Tag Button</h1>
        </a>
      </footer>
    </>
  )
}


